# Generated by Django 5.2.1 on 2025-05-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=10, verbose_name="Пол")),
                ("first_name", models.CharField(max_length=30, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=30, verbose_name="Фамилия")),
                (
                    "phone",
                    models.CharField(max_length=15, verbose_name="Номер телефона"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Эл. почта")),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="Место жительства"),
                ),
                ("photo", models.URLField(max_length=250, verbose_name="Фото")),
            ],
        ),
    ]
