# Generated by Django 5.2.1 on 2025-05-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Номер телефона"),
        ),
    ]
